export const SET_LOADING_TYPE = "SET_LOADING";
export const SET_SECTOR_FILTER_TYPE = "SET_SECTOR_FILTER";
export const SET_AREA_FILTER_TYPE = "SET_AREA_FILTER";
export const SET_TENURE_FILTER_TYPE = "SET_TENURE_FILTER";
export const SET_KEYWORDS_FILTER_TYPE = "SET_KEYWORDS_FILTER";
export const SET_MINPRICE_FILTER_TYPE = "SET_MINPRICE_FILTER";
export const SET_MAXPRICE_FILTER_TYPE = "SET_MAXPRICE_FILTER";
export const SET_ADVERTS_TYPE = "SET_ADVERTS";
