export const SET_SECTOR_FILTER_TYPE = "SET_SECTOR_FILTER";
export const SET_AREA_FILTER_TYPE = "SET_AREA_FILTER";
export const SET_TENURE_FILTER_TYPE = "SET_TENURE_FILTER";
export const SET_KEYWORDS_FILTER_TYPE = "SET_KEYWORDS_FILTER";
export const SET_MINPRICE_FILTER_TYPE = "SET_MINPRICE_FILTER";
export const SET_MAXPRICE_FILTER_TYPE = "SET_MAXPRICE_FILTER";

export const SET_ADVERTS_TYPE = "SET_ADVERTS";
export const SET_SECTORS_TYPE = "SET_SECTORS";
export const SET_AREAS_TYPE = "SET_AREAS";
export const SET_KEYWORDS_TYPE = "SET_KEYWORDS";

export const SET_LOADING_TYPE = "SET_LOADING";
export const SET_FIRSTLOAD_TYPE = "SET_FIRSTLOAD";
export const RESET_FILTERS_TYPE = "RESET_FILTERS";
export const SET_CONTENTS_TYPE = "SET_CONTENTS";
export const SET_TOP_ADVERTS_TYPE = "SET_TOP_ADVERTS";
export const SET_PAGE_TYPE = "SET_PAGE";
