
using System;
using System.Collections.Generic;
using System.Text;
using System.Collections;
using adx;

class AdvertSqlStrings
{
    private static string SelectBaseSql =
        @"SELECT ADV.*, 

        (SELECT STRING_AGG(T3.TITLE, ',') FROM [ADVERT] AS T1
        INNER JOIN [ADVERTAREA] AS T2 ON T1.ID = T2.ADVERT_ID
        INNER JOIN [AREA] AS T3 ON T2.AREA_ID = T3.ID
        WHERE ADV.ID = T1.ID
        ) AS AREAS,

        (SELECT STRING_AGG(T3.TITLE, ',') FROM [ADVERT] AS T1
        INNER JOIN [ADVERTSECTOR] AS T2 ON T1.ID = T2.ADVERT_ID
        INNER JOIN [SECTOR] AS T3 ON T2.SECTOR_ID = T3.ID
        WHERE ADV.ID = T1.ID
        ) AS SECTORS,

        (SELECT STRING_AGG(T3.TITLE, ',') FROM [ADVERT] AS T1
        INNER JOIN [ADVERTTAG] AS T2 ON T1.ID = T2.ADVERT_ID
        INNER JOIN [TAG] AS T3 ON T2.TAG_ID = T3.ID
        WHERE ADV.ID = T1.ID
        ) AS TAGS,

		(SELECT STRING_AGG(T3.TITLE, ',') FROM [ADVERT] AS T1
        INNER JOIN [ADVERTTENURE] AS T2 ON T1.ID = T2.ADVERT_ID
        INNER JOIN [TENURE] AS T3 ON T2.TENURE_ID = T3.ID
        WHERE ADV.ID = T1.ID
        ) AS TENURES,

		(SELECT ISNULL(S.FULLNAME,'') + '|' + ISNULL(S.EMAIL,'')+ '|' + ISNULL(S.PHONE,'') + '|' + ISNULL(S.AVATAR,'') + '|' + 
		ISNULL(S.LINE1,'') + '|' + ISNULL(S.LINE2,'') + '|' + ISNULL(S.CITY,'') + '|' + ISNULL(S.POSTCODE,'') FROM [SELLER] AS S 
		INNER JOIN [ADVERT] AS A ON S.ID = A.SELLER_ID AND A.ID = ADV.ID) AS SELLER

        FROM [ADVERT] AS ADV";

    public static string SelectSql = SelectBaseSql +
        @"
		WHERE 
			(@MIN_PRICE IS NULL OR (ADV.LEASEHOLDPRICE IS NOT NULL AND ADV.LEASEHOLDPRICE >= @MIN_PRICE) OR (ADV.FREEHOLDPRICE IS NOT NULL AND ADV.FREEHOLDPRICE >= @MIN_PRICE)) AND
			(@MAX_PRICE IS NULL OR (ADV.LEASEHOLDPRICE IS NOT NULL AND ADV.LEASEHOLDPRICE <= @MAX_PRICE) OR (ADV.FREEHOLDPRICE IS NOT NULL AND ADV.FREEHOLDPRICE <= @MAX_PRICE)) AND
			(@AREAS IS NULL OR 
				(SELECT COUNT(0) FROM AREA AS T1 INNER JOIN ADVERTAREA AS T2 ON T1.ID = T2.AREA_ID AND T2.ADVERT_ID = ADV.ID 
				INNER JOIN (SELECT VALUE AS VALUE2 FROM STRING_SPLIT(@AREAS, ',')) AS V2 ON T1.TITLE = V2.VALUE2) > 0) AND
			(@SECTORS IS NULL OR 
				(SELECT COUNT(0) FROM SECTOR AS T1 INNER JOIN ADVERTSECTOR AS T2 ON T1.ID = T2.SECTOR_ID AND T2.ADVERT_ID = ADV.ID 
				INNER JOIN (SELECT VALUE AS VALUE2 FROM STRING_SPLIT(@SECTORS, ',')) AS V2 ON T1.TITLE = V2.VALUE2) > 0) AND
			(@TAGS IS NULL OR 
				(SELECT COUNT(0) FROM TAG AS T1 INNER JOIN ADVERTTAG AS T2 ON T1.ID = T2.TAG_ID AND T2.ADVERT_ID = ADV.ID 
				INNER JOIN (SELECT VALUE AS VALUE2 FROM STRING_SPLIT(@TAGS, ',')) AS V2 ON T1.TITLE = V2.VALUE2) > 0) AND
			(@TENURES IS NULL OR 
				(SELECT COUNT(0) FROM TENURE AS T1 INNER JOIN ADVERTTENURE AS T2 ON T1.ID = T2.TENURE_ID AND T2.ADVERT_ID = ADV.ID 
				INNER JOIN (SELECT VALUE AS VALUE2 FROM STRING_SPLIT(@TENURES, ',')) AS V2 ON T1.TITLE = V2.VALUE2) > 0)

        ORDER BY ADV.CREATE_DATE ";

    public static string SelectByPageSql = SelectSql + @"OFFSET(@PAGE-1) * " + Constants.PAGE_SIZE + " ROWS FETCH NEXT " + Constants.PAGE_SIZE + " ROWS ONLY";

    public static string SelectByIdSql = SelectBaseSql + " WHERE CAST(ADV.id AS VARCHAR(50)) = @advert_id";

    //public static string AddSql = @"Insert Into [Advert] () VALUES(@); select CONVERT(varchar(50),scope_identity())";

    //public static string DeleteSql = "Delete From [Advert] Where id = @advert_id";

    //public static string UpdateSql = @"Update [Advert] Set title=@title WHERE id = @id";

}

